### ISSUE TITLE
issues with MSI installer 1.0.0 : Error 1918

### ISSUE THREAD

**Issue by piotrv** [mongodb/mongo-odbc-driver#1]
**ISSUE**:
event application log:

> Product: MongoDB ODBC 1.0.0 -- Error 1918. Error installing ODBC driver: MongoDB ODBC 1.0 Unicode Driver, ODBC error 13: The setup routines for the MongoDB ODBC 1.0 Unicode Driver ODBC driver could not be loaded due to system error code 126: The specified module could not be found. (C:\Program Files\MongoDB\ODBC\1.0\bin\mdbodbcS.dll).. Verify that the file MongoDB ODBC 1.0 Unicode Driver exists and that you can access it. 

> Product: MongoDB ODBC 1.0.0 -- Error 1918. Error installing ODBC driver: MongoDB ODBC 1.0 ANSI Driver, ODBC error 13: The setup routines for the MongoDB ODBC 1.0 ANSI Driver ODBC driver could not be loaded due to system error code 126: The specified module could not be found. (C:\Program Files\MongoDB\ODBC\1.0\bin\mdbodbcS.dll).. Verify that the file MongoDB ODBC 1.0 ANSI Driver exists and that you can access it.

I can replicate this issue both with **MS Windows 7 and Windows 10 x64 (clean) running either as host operating system or guest os on VMware.  Tested with several Intel 64 bit hardware based systems.

**RESOLUTION**:
I figured out that the culprit was the missing of the **Microsoft Visual C++ 2015** runtime components. 
The ODBC driver installer is not checking whether these components have been installed or not.

**Comment by deafgoat** [comment]
Glad to hear. For future reference, we document this at https://docs.mongodb.com/bi-connector/master/tutorial/create-system-dsn/
