### ISSUE TITLE
RPM Installer for mongo-odbc-driver

### ISSUE THREAD

**Issue by n0012** [mongodb/mongo-odbc-driver#144]
I have a use case to leverage the mongo-odbc-driver on an oracle database gateway instance in order to query the Atlas SQL Interface.  Oracle makes a container image available on a fedora image (container-registry.oracle.com/database/free:latest).  

It seems Ubuntu is currently the only supported Linux release of  mongo-odbc-driver.

Any chance you can compile a RPM for Centos/Fedora/RHEL?

**Comment by terakilobyte** [comment]
Hi @n0012 ,

I'm sorry for not getting back to you sooner. At this time, we're not planning to target any other linux distributions in our near or mid-term roadmap.
