### ISSUE TITLE
Unable to install 32bit-Driver

### ISSUE THREAD

**Issue by MarthaZeppelin** [mongodb/mongo-odbc-driver#2]
I'm trying to install from "mongodb-connector-odbc-1.0.0-win-32-bit.msi".
Always fails with:

> Error installing ODBC driver: MongoDB OBDC 1.0 ANSI
driver, ODBC error 13: Die Setup-Routinen für den
MongoDB ODBC 1.0 ANSI Driver ODBC-Trieber konnten
nicht geladen werden. Systemfehlercode 126: Das
angegebene Modul wurde nicht gefunden.
...\mdbodbcS.dll).. Verify that the file MongoDB ODBC ...

But at that point everything seems to be there in C:\Program Files (x86)\MongoDB\ODBC\1.0\bin:

- mdbodbc-installer.exe
- mdbodbca.dll 
- mdbodbca.lib
- mdbodbcS.dll
- mdbodbcS.lib
- mdbodbcw.dll
- mdbodbcw.lib

Everything goes fine when installing "mongodb-connector-odbc-1.0.0-win-64-bit.msi", but that's of no use at the moment since I want to connect from 32bit-Excel.

Any help appreciated.

**Comment by pmeredit** [comment]
Please ensure that you have the 32 bit visual C redistributable installed, that is the most likely problem.

**Comment by MarthaZeppelin** [comment]
Thanks a lot, in fact 32 bit visual C++ redistributable was missing (by accident)
