### ISSUE TITLE
Trying to compile the ODBC Driver as a .so for Linux distribution

### ISSUE THREAD

**Issue by mubeenk** [mongodb/mongo-odbc-driver#4]
I am trying my best to compile the content as a single .so file so I can use the ODBC Driver on the Linux side. Even with cmake/make having no luck. One of the cmake file references absent files. Even with these commented out I am having no luck (not proficient with CMake). Please advise.

**Comment by deafgoat** [comment]
Hi @mubeenk, we're working on creating a version of the driver for Linux and will be releasing one soon.

**Comment by mubeenk** [comment]
Thanks for the reply. So I assume with the current code I can not have driver for Linux. Do you an estimate in mind for the linux version? Just a rough idea. Thanks very much

**Comment by mubeenk** [comment]
Thanks a lot.

**Comment by mubeenk** [comment]
Thanks a lot.

Mubeen
